---
title: "Term Structure Models"
author: "Caleb Vinson"
date: " "
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(stats)
library(minpack.lm)
library(quantmod)
library(vars)
library(ggplot2)
library(knitr)
library(kableExtra)
```


```{r, echo=FALSE}



models <- data.frame(
  Model = c("Vasicek", "CIR", "Hull-White", "Black-Karasinski", "Nelson-Siegel"),
  Uniqueness = c(
    "Mean-reverting with constant volatility.",
    "Non-negativity via square-root volatility.",
    "Time-dependent mean reversion.",
    "Logarithmic modeling of the short rate.",
    "Empirical yield curve representation."
  ),
  Pro = c(
    "Analytical tractability.",
    "Ensures positive rates.",
    "Fits initial yield curve.",
    "Ensures positive rates.",
    "Intuitive interpretation of parameters."
  ),
  Con = c(
    "Allows negative rates.",
    "Difficult to calibrate.",
    "Increased calibration complexity.",
    "Requires numerical solutions.",
    "Lacks arbitrage-free properties."
  )
)

kable(models, format = "latex", longtable = T, booktabs = TRUE, caption = "Comparison of Interest Rate Models") %>%
  kable_styling(full_width = F) %>% 
  column_spec(1, bold = T) %>% 
  column_spec(2, width = "10em") %>%
  column_spec(3, width = "10em") %>%
  column_spec(4, width = "10em")

```

```{r Vasicek Model, echo=TRUE}
r0 <- 0.03
a <- 0.1
b <- 0.05
sigma <- 0.02
T <- 1
dt <- 1/252
n <- T/dt

short_rate <- numeric(n)
short_rate[1] <- r0


set.seed(123)


for (i in 2:n) {
  dW <- rnorm(1, mean = 0, sd = sqrt(dt))
  short_rate[i] <- short_rate[i-1] + a * (b-short_rate[i-1]) * dt + sigma * dW
}

plot(short_rate, 
     type = "l", 
     col = "blue", 
     xlab = "Time Step", 
     ylab = "Interest Rate", 
     main = "Vasicek Model")

```


```{r CIR Model, echo=TRUE}


a <- 0.1     
b <- 0.05    
sigma <- 0.02 
r0 <- 0.03   
T <- 1       
dt <- 1/252  
n <- T/dt    

# short rate
short_rate <- numeric(n)
short_rate[1] <- r0

set.seed(123)
for (i in 2:n) {
  dW <- rnorm(1, mean = 0, sd = sqrt(dt))
  short_rate[i] <- short_rate[i-1] + a * (b - short_rate[i-1]) * dt + sigma * sqrt(short_rate[i-1]) * dW
  short_rate[i] <- max(short_rate[i], 0)  # Ensure non-negativity
}


plot(short_rate, type = "l", col = "darkgreen", xlab = "Time Step", ylab = "Interest Rate", main = "CIR Model Simulation")
```


```{r HW Model, echo = TRUE}


a <- 0.1     
sigma <- 0.02
r0 <- 0.03   
T <- 1       
dt <- 1/252  
n <- T/dt    
short_rate <- numeric(n)
short_rate[1] <- r0


set.seed(123)
for (i in 2:n) {
  dW <- rnorm(1, mean = 0, sd = sqrt(dt))
  theta <- 0.05
  short_rate[i] <- short_rate[i-1] + a * (theta - short_rate[i-1]) * dt + sigma * dW
}

plot(short_rate, type = "l", col = "blue", xlab = "Time Step", ylab = "Interest Rate", main = "Hull-White Model Simulation")
```




```{r Black - Karasinski Model}

a <- 0.1     
sigma <- 0.02 
r0 <- 0.03   
T <- 1       
dt <- 1/252  
n <- T/dt    


short_rate <- numeric(n)
short_rate[1] <- log(r0)


set.seed(123)
for (i in 2:n) {
  dW <- rnorm(1, mean = 0, sd = sqrt(dt))
  short_rate[i] <- short_rate[i-1] + a * (log(0.05) - short_rate[i-1]) * dt + sigma * dW
}


short_rate <- exp(short_rate)


plot(short_rate, type = "l", col = "brown", xlab = "Time Step", ylab = "Interest Rate", main = "Black-Karasinski Model Simulation")

```

```{r Nelson-Sigel}

library(minpack.lm)


nelson_siegel <- function(t, beta0, beta1, beta2, lambda) {
  return(beta0 + beta1 * (1 - exp(-lambda * t)) / (lambda * t) + beta2 * ((1 - exp(-lambda * t)) / (lambda * t) - exp(-lambda * t)))
}


maturity <- c(1, 2, 3, 5, 7, 10)
yield <- c(0.02, 0.025, 0.027, 0.03, 0.032, 0.035)


ns_model <- nlsLM(yield ~ nelson_siegel(maturity, beta0, beta1, beta2, lambda),
                  start = list(beta0 = 0.03, beta1 = -0.01, beta2 = 0.01, lambda = 0.5))

summary(ns_model)


fitted_yield <- predict(ns_model)
plot(maturity, yield, pch = 19, col = "red", xlab = "Maturity (Years)", ylab = "Yield", main = "Nelson-Siegel Yield Curve")
lines(maturity, fitted_yield, col = "blue", lwd = 2)

```

